language: scala
sudo: false
scala:
  - "2.11.7"
jdk:
  - openjdk8
env:
  - NODE_VERSION=6.9.5
cache:
  directories:
    - $HOME/node-v$NODE_VERSION-linux-x64
    - $HOME/.ivy2
    - $HOME/.m2
    - $HOME/.sbt
script:
  - scripts/travis_build
